POST http://localhost:2525/imposters
Content-Type: application/json

{
  "port": 4555,
  "protocol": "http",
  "stubs": [
    {
      "predicates": [
        {
          "contains": {
            "method": "POST",
            "path": "/api/tasks",
            "headers": { "Content-Type": "application/json" },
            "body": "\"title\":\"duplicate\""
          }
        }
      ],
      "responses": [
        {
          "is": {
            "statusCode": 409,
            "headers": { "Content-Type": "application/json" },
            "body": { "error": "duplicate_task" }
          }
        }
      ]
    }
  ]
}

###
POST http://localhost:4555/api/tasks
Content-Type: application/json

{
  "title": "duplicate"
}
